prepare_data.py:
  working_directory: .
  tasks:
    determine_roads_surfaces: true
    generate_tiles_info: true
    generate_labels: true
  input:
    input_folder: data
    input_files:
      roads: swissTLM3D/roads_lines.shp
      roads_param: roads_parameters.xlsx
      forests: swissTLM3D/forests.shp
      aoi: AOI/AOI.shp
      restricted_aoi_training: AOI/training_AOI.shp
  processed_input:
    roads_for_labels: roads_for_OD.shp
  output_folder: outputs_RS
  zoom_level: 18  # keep between 17 and 20

generate_tilesets.py:
  debug_mode: 
    enable: true  # sample of tiles
    nb_tiles_max: 500
  working_directory: outputs_RS
  datasets:
    aoi_tiles: json_inputs/tiles_aoi.geojson
    ground_truth_labels: json_inputs/ground_truth_labels.geojson
    other_labels: json_inputs/other_labels.geojson
    image_source:
      type: XYZ
      location: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage-product/default/2018/3857/{z}/{x}/{y}.jpeg
      srs: "EPSG:3857"
  output_folder: .
  tile_size: 256 # per side, in pixels
  overwrite: False
  n_jobs: 10
  seed: 2
  COCO_metadata:
    year: 2022
    version: 2.0
    description: 2018 SWISSIMAGE RS with segmentation of Feature Class TLM_STRASSE
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: unknown
      url: https://www.swisstopo.admin.ch/fr/home/meta/conditions-generales/geodonnees/ogd.html

train_model.py:
  debug_mode: True
  working_directory: outputs_RS
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_training_images
  COCO_files: # relative paths, w/ respect to the working_folder
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
  detectron2_config_file: ../detectron2_config_3bands.yaml # path relative to the working_folder
  model_weights:
    model_zoo_checkpoint_url: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml

make_detections.py:
  working_directory: outputs_RS
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_detection_images
  COCO_files: # relative paths, w/ respect to the working_folder
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
    oth: COCO_oth.json
  detectron2_config_file: ../detectron2_config_3bands.yaml # path relative to the working_folder
  model_weights:
    pth_file: logs/model_0010999.pth
  image_metadata_json: img_metadata.json
  rdp_simplification: # rdp = Ramer-Douglas-Peucker
    enabled: true
    epsilon: 0.75 # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05

assess_detections.py:
  working_directory: outputs_RS
  datasets:
    ground_truth_labels: json_inputs/ground_truth_labels.geojson
    other_labels: json_inputs/other_labels.geojson
    split_aoi_tiles: split_aoi_tiles.geojson
    detections:
      trn: trn_detections_at_0dot05_threshold.gpkg
      val: val_detections_at_0dot05_threshold.gpkg
      tst: tst_detections_at_0dot05_threshold.gpkg
      oth: oth_detections_at_0dot05_threshold.gpkg
  output_folder: .
  iou_threshold: 0.1