######################################################################
### configuration file to identify and monitor quarry through time ### 
######################################################################
# Refer to the README.md provided for more details

# Track object in different datasets over years
detection_monitoring.py:  
  years: [2017, 2020]                         # Provide a list of years used for detection
  datasets:
    detection: ../input/input-dm/oth_predictions_at_0dot3_threshold_year-{year}_score-0dot95_area-5000_elevation-1200_distance-10.geojson  # Final detection file, produced by prediction_filter.py !!! Change value in squared bracket 
  output_folder: ../output/output-dm

# Plots
plots.py:  
  object_id: [ID_OBJECT1, ID_OBJECT2, ID_OBJECT3,...]       # Provide a list of id_object defined by detection_monitoring.py
  plots: ['area-year'] 
  datasets:
    detection: ../output/output-dm/quarry_times.geojson     # Object tracking file, produced by detection_monitoring.py
  output_folder: ../output/output-dm/plots