generate_training_sets.py:
  datasets:
    lakes_shapefile: https://ge.ch/sitg/geodata/SITG/OPENDATA/3951/SHP_GEO_LAC_LEMAN.zip
    parcels_shapefile: https://ge.ch/sitg/geodata/SITG/OPENDATA/8450/SHP_CAD_PARCELLE_MENSU.zip
    swimmingpools_shapefile: https://ge.ch/sitg/geodata/SITG/OPENDATA/1836/SHP_CAD_PISCINE.zip
    orthophotos_map_image_layer_url: https://ge.ch/sitgags2/rest/services/RASTER/ORTHOPHOTOS_2018/MapServer
    OK_z18_tile_IDs_csv: data/OK_z18_tile_IDs.csv
  folders:
    output: output
  tile_size: 256 # per side, in pixels
  save_image_metadata: True
  overwrite: False
  n_jobs: 10
  COCO_metadata:
    year: 2020
    version: 1.0
    description: 2018 orthophotos w/ Swimming Pool segmentations
    contributor: Système d'information du territoire à Genève (SITG)
    url: https://ge.ch/sitg
    license:
      name: Open Data
      url: https://ge.ch/sitg/media/sitg/files/documents/conditions_generales_dutilisation_des_donnees_et_produits_du_sitg_en_libre_acces.pdf


assess_predictions.py:
  n_jobs: 10
  datasets:
    swimmingpools_shapefile: output/SHP_CAD_PISCINE.zip
    image_metadata_json: output/img_metadata.json
    swimmingpool_tiles_geojson: output/swimmingpool_tiles.geojson # tiles including at least one swimming pool, split in trn/val/tst subsets
    aoi_tiles_geojson: output/parcels_z18_tiles.geojson # aoi = Area of Interest
    predictions:
      trn: output/trn_predictions_at_0dot05_threshold.pkl
      val: output/val_predictions_at_0dot05_threshold.pkl
      tst: output/tst_predictions_at_0dot05_threshold.pkl
      all: output/all_predictions_at_0dot05_threshold.pkl
  folders:
    cache: cache
    output: output

