prepare_GE_data.py:
  datasets:
    lakes_shapefile: https://ge.ch/sitg/geodata/SITG/OPENDATA/3951/SHP_GEO_LAC_LEMAN.zip
    parcels_shapefile: https://ge.ch/sitg/geodata/SITG/OPENDATA/8450/SHP_CAD_PARCELLE_MENSU.zip
    swimmingpools_shapefile: https://ge.ch/sitg/geodata/SITG/OPENDATA/1836/SHP_CAD_PISCINE.zip
    OK_z18_tile_IDs_csv: data/GE/OK_z18_tile_IDs.csv
  output_folder: output_GE_v2

generate_training_sets.py:
  debug_mode: True
  datasets:
    aoi_tiles_geojson: output_GE_v2/aoi_z18_tiles.geojson
    ground_truth_labels_geojson: output_GE_v2/ground_truth_labels.geojson
    other_labels_geojson: output_GE_v2/other_labels.geojson
    orthophotos_web_service:
      type: MIL # supported values: 1. MIL = Map Image Layer 2. WMS
      url: https://ge.ch/sitgags2/rest/services/RASTER/ORTHOPHOTOS_2018/MapServer
      srs: "EPSG:3857"
  output_folder: output_GE_v2
  tile_size: 256 # per side, in pixels
  save_image_metadata: True
  overwrite: False
  n_jobs: 10
  COCO_metadata:
    year: 2020
    version: 1.0
    description: 2018 orthophotos w/ Swimming Pool segmentations
    contributor: Système d'information du territoire à Genève (SITG)
    url: https://ge.ch/sitg
    license:
      name: Open Data
      url: https://ge.ch/sitg/media/sitg/files/documents/conditions_generales_dutilisation_des_donnees_et_produits_du_sitg_en_libre_acces.pdf
  
assess_predictions.py:
  n_jobs: 10
  datasets:
    ground_truth_labels_geojson: output_GE_v2/ground_truth_labels.geojson
    other_labels_geojson: output_GE_v2/other_labels.geojson
    image_metadata_json: output_GE_v2/img_metadata.json
    splitted_aoi_tiles_geojson: output_GE_v2/splitted_aoi_tiles.geojson # aoi = Area of Interest
    predictions:
      trn: output_GE_v2/trn_predictions_at_0dot05_threshold.pkl
      val: output_GE_v2/val_predictions_at_0dot05_threshold.pkl
      tst: output_GE_v2/tst_predictions_at_0dot05_threshold.pkl
      oth: output_GE_v2/oth_predictions_at_0dot05_threshold.pkl
  output_folder: output_GE_v2