generate_training_sets_NE.py:
  datasets:
    ground_truth_sectors_shapefile: data-update/Sectors_groundtruth.shp
    other_sectors_shapefile: data-update/Sectors_other.shp
    ground_truth_swimming_pools_shapefile: data-update/sp_gt_missing_manuell.shp
    other_swimming_pools_shapefile: data-update/Swimmingpools_other.shp
    orthophotos_web_map_service:
      url: https://sitn.ne.ch/mapproxy95/service
      layers: ortho2019
      srs: "EPSG:900913"
  folders:
    output: output-comb
  tile_size: 256 # per side, in pixels
  save_image_metadata: True
  overwrite: False
  n_jobs: 100
  COCO_metadata:
    year: 2020
    version: 1.0
    description: 2019 orthophotos w/ Swimming Pool segmentations
    contributor: Système d'information du territoire Neuchâtelois (SITN)
    url: https://sitn.ne.ch
    license:
      name: Unknown
      url: 


assess_predictions_NE.py:
  n_jobs: 100
  datasets:
    labels_geojson: output-comb/labels-NE-manuell-fuse.geojson
    image_metadata_json: output-comb/img_metadata.json
    OK_tiles_geojson: output-comb/OK_tiles.geojson # tiles including at least one swimming pool, split in trn/val/tst subsets
    aoi_tiles_geojson: output-comb/aoi_z18_tiles.geojson # aoi = Area of Interest
    predictions:
      trn: output-comb/trn_predictions_at_0dot05_threshold.pkl
      val: output-comb/val_predictions_at_0dot05_threshold.pkl
      tst: output-comb/tst_predictions_at_0dot05_threshold.pkl
      all: output-comb/all_predictions_at_0dot05_threshold.pkl
  folders:
    output: output-comb/assessment-GEuNE

