prepare_NE_data.py:
  datasets:
    ground_truth_sectors_shapefile: data/NE/Sectors_groundtruth.shp
    other_sectors_shapefile: data/NE/Sectors_other.shp
    ground_truth_swimming_pools_shapefile: data/NE/sp_gt_missing_manuell.shp
    other_swimming_pools_shapefile: data/NE/Swimmingpools_other.shp
  zoom_level: 18
  output_folder: output_NE_v2

generate_training_sets.py:
  debug_mode: True
  datasets:
    aoi_tiles_geojson: output_NE_v2/aoi_z18_tiles.geojson
    ground_truth_labels_geojson: output_NE_v2/ground_truth_labels.geojson
    other_labels_geojson: output_NE_v2/other_labels.geojson
    orthophotos_web_service:
      type: WMS # supported values: 1. MIL = Map Image Layer 2. WMS
      url: https://sitn.ne.ch/mapproxy95/service
      layers: ortho2019
      srs: "EPSG:3857"
  folders:
    output: output_NE_v2
  tile_size: 256 # per side, in pixels
  save_image_metadata: True
  overwrite: True
  n_jobs: 10
  COCO_metadata:
    year: 2020
    version: 1.0
    description: 2019 orthophotos w/ Swimming Pool segmentations
    contributor: Système d'information du territoire Neuchâtelois (SITN)
    url: https://sitn.ne.ch
    license:
      name: Unknown
      url: 
  
assess_predictions.py:
  n_jobs: 10
  datasets:
    swimmingpools_shapefile: output_NE_v2/SHP_CAD_PISCINE.zip
    ground_truth_labels_geojson:
    other_labels_geojson:
    image_metadata_json: output_NE_v2/img_metadata.json
    swimmingpool_tiles_geojson: output_NE_v2/swimmingpool_tiles.geojson # tiles including at least one swimming pool, split in trn/val/tst subsets
    aoi_tiles_geojson: output_NE_v2/parcels_z18_tiles.geojson # aoi = Area of Interest
    predictions:
      trn: output_NE_v2/trn_predictions_at_0dot05_threshold.pkl
      val: output_NE_v2/val_predictions_at_0dot05_threshold.pkl
      tst: output_NE_v2/tst_predictions_at_0dot05_threshold.pkl
      oth: output_NE_v2/oth_predictions_at_0dot05_threshold.pkl
  folders:
    output_GE: output_NE_v2