generate_training_sets_NE.py:
  datasets:
    ground_truth_sectors_shapefile: data/downloader/swimming-pool-detector/data/Secteurs_ground_truth.shp
    other_sectors_shapefile: data/downloader/swimming-pool-detector/Secteurs_autres.shp
    #swimmingpools_shapefile: https://ge.ch/sitg/geodata/SITG/OPENDATA/1836/SHP_CAD_PISCINE.zip
    #orthophotos_map_image_layer_url: https://ge.ch/sitgags2/rest/services/RASTER/ORTHOPHOTOS_2018/MapServer
    #OK_z18_tile_IDs_csv: data/OK_z18_tile_IDs.csv
    wms_url: https://sitn.ne.ch/mapproxy95/service
    layers: ortho2019
    srs: "EPSG:900913"
  folders:
    output: output-NE
  tile_size: 256 # per side, in pixels
  save_image_metadata: True
  overwrite: False
  n_jobs: 10
  # COCO_metadata:
  #   year: 2020
  #   version: 1.0
  #   description: 2018 orthophotos w/ Swimming Pool segmentations
  #   contributor: Système d'information du territoire à Genève (SITG)
  #   url: https://ge.ch/sitg
  #   license:
  #     name: Open Data
  #     url: https://ge.ch/sitg/media/sitg/files/documents/conditions_generales_dutilisation_des_donnees_et_produits_du_sitg_en_libre_acces.pdf


assess_predictions.py:
  n_jobs: 10
  datasets:
    swimmingpools_shapefile: output/SHP_CAD_PISCINE.zip
    image_metadata_json: output/img_metadata.json
    swimmingpool_tiles_geojson: output/swimmingpool_tiles.geojson # tiles including at least one swimming pool, split in trn/val/tst subsets
    aoi_tiles_geojson: output/parcels_z18_tiles.geojson # aoi = Area of Interest
    predictions:
      trn: output/trn_predictions_at_0dot05_threshold.pkl
      val: output/val_predictions_at_0dot05_threshold.pkl
      tst: output/tst_predictions_at_0dot05_threshold.pkl
      all: output/all_predictions_at_0dot05_threshold.pkl
  folders:
    output: output

