version: "3"

services:
  stdl-objdet:
    build: .
    volumes:
      - ./examples:/app/examples
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: /bin/bash