prepare_data.py:
  datasets:
    ground_truth_sectors_shapefile: data/Ground_truth_sectors.shp
    other_sectors_shapefile: data/Other_sector.shp
    ground_truth_swimming_pools_shapefile: data/Ground_truth_swimming_pools.shp
    other_swimming_pools_shapefile: data/Other_swimming_pools.shp
  zoom_level: 18
  output_folder: output_NE

generate_tilesets.py:
  debug_mode: 
    enable: False  # sample of tiles
    nb_tiles_max: 100
  working_directory: output_NE
  datasets:
    aoi_tiles: aoi_z18_tiles.geojson
    ground_truth_labels: ground_truth_labels.geojson
    other_labels: other_labels.geojson
    image_source:
      type: WMS # supported values: 1. MIL = Map Image Layer 2. WMS 3. XYZ 4. FOLDER
      location: https://sitn.ne.ch/mapproxy95/service
      layers: ortho2019
      srs: "EPSG:3857"
  # empty_tiles:            # add empty tiles to datasets
  #   tiles_frac: 0.5       # fraction (relative to the number of tiles intersecting labels) of empty tiles to add
  #   frac_trn: 0.75        # fraction of empty tiles to add to the trn dataset, then the remaining tiles will be split in 2 and added to tst and val datasets
  #   keep_oth_tiles: True # keep tiles in oth dataset not intersecting oth labels
  output_folder: .
  tile_size: 256 # per side, in pixels
  overwrite: True
  n_jobs: 10
  COCO_metadata:
    year: 2020
    version: 1.0
    description: 2019 orthophotos w/ Swimming Pool segmentations
    contributor: Système d'information du territoire Neuchâtelois (SITN)
    url: https://sitn.ne.ch
    license:
      name: Unknown
      url:
        
train_model.py:
  working_directory: output_NE
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_training_images
  COCO_files: # relative paths, w/ respect to the working_folder
      trn: COCO_trn.json
      val: COCO_val.json
      tst: COCO_tst.json
  detectron2_config_file: '../detectron2_config_NE.yaml' # path relative to the working_folder
  model_weights:
      model_zoo_checkpoint_url: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
        
make_detections.py:
  working_directory: output_NE
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_detection_images
  COCO_files: # relative paths, w/ respect to the working_folder
      trn: COCO_trn.json
      val: COCO_val.json
      tst: COCO_tst.json
      oth: COCO_oth.json
  detectron2_config_file: '../detectron2_config_NE.yaml' # path relative to the working_folder
  model_weights:
      pth_file: './logs/model_final.pth'
  image_metadata_json: img_metadata.json
  rdp_simplification: # rdp = Ramer-Douglas-Peucker
    enabled: true
    epsilon: 0.5 # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05
  remove_det_overlap: False  # if several detections overlap (IoU > 0.5), only the one with the highest confidence score is retained
  
assess_detections.py:
  working_directory: output_NE
  datasets:
    ground_truth_labels: ground_truth_labels.geojson
    other_labels: other_labels.geojson
    split_aoi_tiles: split_aoi_tiles.geojson # aoi = Area of Interest
    categories: category_ids.json
    detections:
      trn: trn_detections_at_0dot05_threshold.gpkg
      val: val_detections_at_0dot05_threshold.gpkg
      tst: tst_detections_at_0dot05_threshold.gpkg
      oth: oth_detections_at_0dot05_threshold.gpkg
  output_folder: .
    metrics_method: micro-average   # 1: macro-average ; 3: macro-weighted-average ; 2: micro-average