prepare_data.py:
  working_dir: .
  output_dir:
    vectors: outputs/instance_segmentation/formatted_labels
    clipped_tiles: outputs/instance_segmentation/clipped_tiles
  tile_dir: outputs/rgb_images
  initial_image_dir: data/STDL_Plans_georeferences
  initial_files:
    border_points: data/ground_truth/Realite_terrain_Polygone/PL_realite_terrain_polygones.shp
    bbox: data/ground_truth/Realite_terrain_Box/PL_realite_terrain_box.shp
    plan_scales: data/plan_scales.xlsx
  tile_suffix: _geo.tif
  convert_images: True
  overwrite: False


generate_tilesets.py:
  debug_mode: 
    enable: False     # sample of tiles
    nb_tiles_max: 10
  working_directory: outputs/instance_segmentation
  datasets:
    aoi_tiles: formatted_labels/subtiles.gpkg
    ground_truth_labels: formatted_labels/ground_truth_labels.gpkg
    image_source:
      type: FOLDER
      location: clipped_tiles/subtiles
      srs: 2056
  output_folder: object_detector
  overwrite: True
  n_jobs: 10
  COCO_metadata:
    year: 1800-1900
    version: 1.0
    description: Points limites des anciens plans cadastraux
    contributor: Canton of Fribourg
    url: none
    license:
      name: unknown
      url: unknown
  seed: 7


train_model.py:
  debug_mode: false
  working_directory: outputs/instance_segmentation/object_detector
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_training_images
  COCO_files:         # relative paths, w/ respect to the working_folder
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
  detectron2_config_file: ../../../config/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    model_zoo_checkpoint_url: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml


make_detections.py:
  working_directory: outputs/instance_segmentation/object_detector
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files:           # relative paths, w/ respect to the working_folder
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
  detectron2_config_file: ../../../config/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    pth_file: logs/model_0006499.pth # trained model minimizing the validation loss, monitor via tensorboard (tensorboard --logdir </logs>)
  image_metadata_json: img_metadata.json
  rdp_simplification:   # rdp = Ramer-Douglas-Peucker
    enabled: False
    epsilon: 0.05       # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05


assess_detections.py:
  working_directory: outputs/instance_segmentation/object_detector
  output_folder: .
  metrics_method: micro-average
  datasets:
    ground_truth_labels: ../formatted_labels/ground_truth_labels.gpkg
    image_metadata_json: img_metadata.json
    split_aoi_tiles: split_aoi_tiles.geojson # aoi = Area of Interest
    categories: category_ids.json
    detections:
      trn: trn_detections_at_0dot05_threshold.gpkg
      val: val_detections_at_0dot05_threshold.gpkg
      tst: tst_detections_at_0dot05_threshold.gpkg


post_processing.py:
  working_dir: outputs/instance_segmentation
  input_dir: object_detector
  output_dir: post_processing
  detections:
    trn: trn_detections_at_0dot05_threshold.gpkg
    val: val_detections_at_0dot05_threshold.gpkg
    tst: tst_detections_at_0dot05_threshold.gpkg
  subtiles: formatted_labels/subtiles.gpkg
  tiles: formatted_labels/tiles.gpkg
  category_ids_json: category_ids.json
  score: 0.65
  keep_datasets: False